### ISSUE TITLE
aws-cli ses rules - operation unavailable

### ISSUE THREAD

**Issue by lxm7** [nealalan/AWS-Email-Forwarder#1]
Really informative write up, thanks. Just near the end and would be nice to complete it all via the cli.

Stuck at https://nealalan.github.io/AWS-Email-Forwarder/#34-create-verify--activate-a-blank-ses-rule-set -  where im getting An `error occurred (InvalidAction) operations unavailable`

Should i be using sesv2 as per docs here for step 34 - https://docs.aws.amazon.com/ses/latest/dg/creating-configuration-sets.html#config-sets-create-cli? 

aws-cli/2.5.2 Python/3.9.11 Darwin/18.7.0
OS: 10.14

**Comment by lxm7** [comment]
eu-* zones dont have the email receiving option, fml

**Comment by nealalan** [comment]
@lxm7 Did that end up being the issue for you? I wrote this up over 2 years ago and happy to see someone saw it. I still have the email forwarding from domains I own happening daily!

**Comment by lxm7** [comment]
@nealalan its all good thanks, i had got it running prior to when i wrote my last comment, ha. Its been a while since i used AWS for this stuff and forget that certain subset of features, even in 2022, are only available in certain zones, the email receiving being one of them. Thanks again, that write up was super useful, esp using the command line only.

Solution: use a `us-*` zone that shows `email receiving` in the side menu in SES, in order to continue from step 34 onwards

**Comment by lxm7** [comment]
the fix was to use a us-* zone that shows `email receiving` in the side menu in SES, in order to continue at step 34 and onwards
